interval = 1800
splay = 1800
splay_first_run = 0
log_level = 'warn'
report_to_stdout = true

[chef_license]
acceptance = "undefined"

[automate]
enable = false
server_url = "http://a2-dev.test"
token = 'none'
user = 'none'
